### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by aoussarmustapha** [cybernet/CyBerFuN-xBTiT#1]
Hello,
I've followed all the instructions to install xBTiT and has been installed successfully. The SMF: http://mydomain.com/smf/index.php worked fine!
IPB: http://mydomain.com/ipb/ worked fine!
but the xBTiT homepage http://mydomain.com/index.php doesn't work. I got a blank page.

Why? Where can I find error logs file?

Thank you!

**Comment by cybernet** [comment]
i'm sorry that i haven't updated the description, but the new project is located here - https://github.com/cybyd/cybyd
